### ISSUE TITLE
Integration of new schema mapping

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/dlr-riesgos-frontend#138]
New transition matrix already used in staging.

- [x] Frontend: exposure model `valparaiso downscaled` shall no longer be offered as an option, but remains available for now in the wps
- [x] enable exposure model `Medina` for TS damage & test
- [x] make sure that returned data from deus conforms to medina schema

**Comment by MichaelLangbein** [comment]
Currently there is an error thrown when activating Medina for Chile:

Request:
```xml
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" service="WPS" version="1.0.0">
    <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">org.n52.gfz.riesgos.algorithm.impl.DeusProcess</p0:Identifier>
    <wps:DataInputs>
        <wps:Input>
            <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">schema</p0:Identifier>
            <p0:Title xmlns:p0="http://www.opengis.net/ows/1.1">schema</p0:Title>
            <p0:Abstract xmlns:p0="http://www.opengis.net/ows/1.1"></p0:Abstract>
            <wps:Data>
                <wps:LiteralData>SARA_v1.0</wps:LiteralData>
            </wps:Data>
        </wps:Input>
        <wps:Input>
            <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">fragility</p0:Identifier>
            <p0:Title xmlns:p0="http://www.opengis.net/ows/1.1">fragility</p0:Title>
            <p0:Abstract xmlns:p0="http://www.opengis.net/ows/1.1"></p0:Abstract>
            <wps:Reference p1:href="https://rz-vm140.gfz-potsdam.de:8443/wps/RetrieveResultServlet?id=5e9c5f30-6005-40a5-8e45-3cab21c594bfselectedRows.3a8e4e7b-aed4-4f5b-8288-b9d61810f7a9" xmlns:p1="http://www.w3.org/1999/xlink" method="GET" mimeType="application/json" />
        </wps:Input>
        <wps:Input>
            <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">intensity</p0:Identifier>
            <p0:Title xmlns:p0="http://www.opengis.net/ows/1.1">intensity</p0:Title>
            <p0:Abstract xmlns:p0="http://www.opengis.net/ows/1.1"></p0:Abstract>
            <wps:Reference p2:href="http://tsunami-wps.awi.de/outputs/3e414bd8-bcbb-11ec-8e0d-02420a030102/input.xml" xmlns:p2="http://www.w3.org/1999/xlink" method="GET" mimeType="text/xml" />
        </wps:Input>
        <wps:Input>
            <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">exposure</p0:Identifier>
            <p0:Title xmlns:p0="http://www.opengis.net/ows/1.1">exposure</p0:Title>
            <p0:Abstract xmlns:p0="http://www.opengis.net/ows/1.1"></p0:Abstract>
            <wps:Reference p3:href="https://rz-vm140.gfz-potsdam.de:8443/wps/RetrieveResultServlet?id=235c0415-fc21-4d25-bcad-eee2f0968eb1merged_output.1a540c29-6d30-48a6-9a93-e0c5959ae7ad" xmlns:p3="http://www.w3.org/1999/xlink" method="GET" mimeType="application/json" />
        </wps:Input>
    </wps:DataInputs>
    <wps:ResponseForm>
        <wps:ResponseDocument storeExecuteResponse="true" status="true">
            <wps:Output mimeType="application/WMS" asReference="false">
                <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">shapefile_summary</p0:Identifier>
            </wps:Output>
            <wps:Output mimeType="application/WMS" asReference="false">
                <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">shapefile_summary</p0:Identifier>
            </wps:Output>
            <wps:Output mimeType="application/WMS" asReference="false">
                <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">shapefile_summary</p0:Identifier>
            </wps:Output>
        </wps:ResponseDocument>
    </wps:ResponseForm>
</wps:Execute>
```


Error:
```
From https://rz-vm140.gfz-potsdam.de:8443/wps/RetrieveResultServlet?id=9d310794-1a65-4d6e-87af-3cf3e4854a73:  <?xml version='1.0' encoding='UTF-8'?><wps:ExecuteResponse xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows/1.1" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsExecute_response.xsd" serviceInstance="https://rz-vm140.gfz-potsdam.de:8443/wps/WebProcessingService?REQUEST=GetCapabilities&amp;SERVICE=WPS" xml:lang="en-US" service="WPS" version="1.0.0" statusLocation="https://rz-vm140.gfz-potsdam.de:8443/wps/RetrieveResultServlet?id=9d310794-1a65-4d6e-87af-3cf3e4854a73"><wps:Process wps:processVersion="1.0.0"><ows:Identifier>org.n52.gfz.riesgos.algorithm.impl.DeusProcess</ows:Identifier><ows:Title>DeusProcess</ows:Title></wps:Process><wps:Status creationTime="2022-04-15T13:31:38.887Z"><wps:ProcessFailed><ows:ExceptionReport version="1.0.0"><ows:Exception exceptionCode="NoApplicableCode"><ows:ExceptionText>org.n52.wps.server.ExceptionReport: There is an error on stderr: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/share/git/deus/gpdexposure.py", line 396, in update_df
    list_of_series = dataframe.apply(self.update_series, axis=1)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 6906, in apply
    return op.get_result()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 292, in apply_standard
    self.apply_series_generator()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 321, in apply_series_generator
    results[i] = self.f(v)
  File "/usr/share/git/deus/gpdexposure.py", line 412, in update_series
    schema_mapper=self.schema_mapper,
  File "/usr/share/git/deus/gpdexposure.py", line 180, in map_exposure
    n_buildings=1.0,
  File "/usr/share/git/deus/schemamapping.py", line 224, in map_schema
    source_schema, source_taxonomy, source_damage_state, target_schema
  File "/usr/share/git/deus/schemamapping.py", line 256, in _map_schema_1
    source_schema, source_taxonomy, source_damage_state, target_schema
  File "/usr/share/git/deus/schemamapping.py", line 325, in _do_map_schema_1
    target_schema=target_schema,
  File "/usr/share/git/deus/schemamapping.py", line 276, in _map_schema_1_just_taxonomy
    target_schema=target_schema,
  File "/usr/share/git/deus/schemamapping.py", line 307, in _do_map_schema_1_just_taxonomy
    ).format(source_taxonomy)
Exception: ('There is no data for the schema mapping for the source taxonomy CR-LWAL-DNO-H1-3', 'occurred at index 0')
```

The above exception was the direct cause of the following exception:
```
Traceback (most recent call last):
  File "deus.py", line 99, in &lt;module>
    main()
  File "deus.py", line 92, in main
    worker.run()
  File "/usr/share/git/deus/tellus.py", line 58, in run
    self.loss_provider,
  File "/usr/share/git/deus/gpdexposure.py", line 146, in update_exposure_transitions_and_losses
    pool.map(updater.update_df, splitted_exposure),
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
Exception: ('There is no data for the schema mapping for the source taxonomy CR-LWAL-DNO-H1-3', 'occurred at index 0')
org.n52.gfz.riesgos.exceptions.NonEmptyStderrException: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/share/git/deus/gpdexposure.py", line 396, in update_df
    list_of_series = dataframe.apply(self.update_series, axis=1)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 6906, in apply
    return op.get_result()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 292, in apply_standard
    self.apply_series_generator()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 321, in apply_series_generator
    results[i] = self.f(v)
  File "/usr/share/git/deus/gpdexposure.py", line 412, in update_series
    schema_mapper=self.schema_mapper,
  File "/usr/share/git/deus/gpdexposure.py", line 180, in map_exposure
    n_buildings=1.0,
  File "/usr/share/git/deus/schemamapping.py", line 224, in map_schema
    source_schema, source_taxonomy, source_damage_state, target_schema
  File "/usr/share/git/deus/schemamapping.py", line 256, in _map_schema_1
    source_schema, source_taxonomy, source_damage_state, target_schema
  File "/usr/share/git/deus/schemamapping.py", line 325, in _do_map_schema_1
    target_schema=target_schema,
  File "/usr/share/git/deus/schemamapping.py", line 276, in _map_schema_1_just_taxonomy
    target_schema=target_schema,
  File "/usr/share/git/deus/schemamapping.py", line 307, in _do_map_schema_1_just_taxonomy
    ).format(source_taxonomy)
Exception: ('There is no data for the schema mapping for the source taxonomy CR-LWAL-DNO-H1-3', 'occurred at index 0')
```

The above exception was the direct cause of the following exception:
```
Traceback (most recent call last):
  File "deus.py", line 99, in &lt;module>
    main()
  File "deus.py", line 92, in main
    worker.run()
  File "/usr/share/git/deus/tellus.py", line 58, in run
    self.loss_provider,
  File "/usr/share/git/deus/gpdexposure.py", line 146, in update_exposure_transitions_and_losses
    pool.map(updater.update_df, splitted_exposure),
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
Exception: ('There is no data for the schema mapping for the source taxonomy CR-LWAL-DNO-H1-3', 'occurred at index 0')

    at org.n52.gfz.riesgos.stderrhandler.PythonTracebackStderrHandler.handleStderr(PythonTracebackStderrHandler.java:57)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService$InnerRunContext.handleStderr(BaseGfzRiesgosService.java:741)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService$InnerRunContext.runExecutableInContext(BaseGfzRiesgosService.java:613)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService$InnerRunContext.runExecutable(BaseGfzRiesgosService.java:540)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService$InnerRunContext.run(BaseGfzRiesgosService.java:438)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService$InnerRunContext.access$100(BaseGfzRiesgosService.java:405)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService.run(BaseGfzRiesgosService.java:310)
    at org.n52.wps.server.request.ExecuteRequestV100.call(ExecuteRequestV100.java:678)
    at org.n52.wps.server.request.ExecuteRequestV100.call(ExecuteRequestV100.java:97)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)</ows:ExceptionText></ows:Exception></ows:ExceptionReport></wps:ProcessFailed></wps:Status></wps:ExecuteResponse>
```
Stack:
```
Error: From https://rz-vm140.gfz-potsdam.de:8443/wps/RetrieveResultServlet?id=9d310794-1a65-4d6e-87af-3cf3e4854a73:  <?xml version='1.0' encoding='UTF-8'?><wps:ExecuteResponse xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows/1.1" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsExecute_response.xsd" serviceInstance="https://rz-vm140.gfz-potsdam.de:8443/wps/WebProcessingService?REQUEST=GetCapabilities&amp;SERVICE=WPS" xml:lang="en-US" service="WPS" version="1.0.0" statusLocation="https://rz-vm140.gfz-potsdam.de:8443/wps/RetrieveResultServlet?id=9d310794-1a65-4d6e-87af-3cf3e4854a73"><wps:Process wps:processVersion="1.0.0"><ows:Identifier>org.n52.gfz.riesgos.algorithm.impl.DeusProcess</ows:Identifier><ows:Title>DeusProcess</ows:Title></wps:Process><wps:Status creationTime="2022-04-15T13:31:38.887Z"><wps:ProcessFailed><ows:ExceptionReport version="1.0.0"><ows:Exception exceptionCode="NoApplicableCode"><ows:ExceptionText>org.n52.wps.server.ExceptionReport: There is an error on stderr: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/share/git/deus/gpdexposure.py", line 396, in update_df
    list_of_series = dataframe.apply(self.update_series, axis=1)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 6906, in apply
    return op.get_result()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 292, in apply_standard
    self.apply_series_generator()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 321, in apply_series_generator
    results[i] = self.f(v)
  File "/usr/share/git/deus/gpdexposure.py", line 412, in update_series
    schema_mapper=self.schema_mapper,
  File "/usr/share/git/deus/gpdexposure.py", line 180, in map_exposure
    n_buildings=1.0,
  File "/usr/share/git/deus/schemamapping.py", line 224, in map_schema
    source_schema, source_taxonomy, source_damage_state, target_schema
  File "/usr/share/git/deus/schemamapping.py", line 256, in _map_schema_1
    source_schema, source_taxonomy, source_damage_state, target_schema
  File "/usr/share/git/deus/schemamapping.py", line 325, in _do_map_schema_1
    target_schema=target_schema,
  File "/usr/share/git/deus/schemamapping.py", line 276, in _map_schema_1_just_taxonomy
    target_schema=target_schema,
  File "/usr/share/git/deus/schemamapping.py", line 307, in _do_map_schema_1_just_taxonomy
    ).format(source_taxonomy)
Exception: ('There is no data for the schema mapping for the source taxonomy CR-LWAL-DNO-H1-3', 'occurred at index 0')
```

The above exception was the direct cause of the following exception:
```
Traceback (most recent call last):
  File "deus.py", line 99, in &lt;module>
    main()
  File "deus.py", line 92, in main
    worker.run()
  File "/usr/share/git/deus/tellus.py", line 58, in run
    self.loss_provider,
  File "/usr/share/git/deus/gpdexposure.py", line 146, in update_exposure_transitions_and_losses
    pool.map(updater.update_df, splitted_exposure),
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
Exception: ('There is no data for the schema mapping for the source taxonomy CR-LWAL-DNO-H1-3', 'occurred at index 0')
org.n52.gfz.riesgos.exceptions.NonEmptyStderrException: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/share/git/deus/gpdexposure.py", line 396, in update_df
    list_of_series = dataframe.apply(self.update_series, axis=1)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 6906, in apply
    return op.get_result()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 186, in get_result
    return self.apply_standard()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 292, in apply_standard
    self.apply_series_generator()
  File "/usr/local/lib/python3.7/site-packages/pandas/core/apply.py", line 321, in apply_series_generator
    results[i] = self.f(v)
  File "/usr/share/git/deus/gpdexposure.py", line 412, in update_series
    schema_mapper=self.schema_mapper,
  File "/usr/share/git/deus/gpdexposure.py", line 180, in map_exposure
    n_buildings=1.0,
  File "/usr/share/git/deus/schemamapping.py", line 224, in map_schema
    source_schema, source_taxonomy, source_damage_state, target_schema
  File "/usr/share/git/deus/schemamapping.py", line 256, in _map_schema_1
    source_schema, source_taxonomy, source_damage_state, target_schema
  File "/usr/share/git/deus/schemamapping.py", line 325, in _do_map_schema_1
    target_schema=target_schema,
  File "/usr/share/git/deus/schemamapping.py", line 276, in _map_schema_1_just_taxonomy
    target_schema=target_schema,
  File "/usr/share/git/deus/schemamapping.py", line 307, in _do_map_schema_1_just_taxonomy
    ).format(source_taxonomy)
Exception: ('There is no data for the schema mapping for the source taxonomy CR-LWAL-DNO-H1-3', 'occurred at index 0')
```

The above exception was the direct cause of the following exception:
```
Traceback (most recent call last):
  File "deus.py", line 99, in &lt;module>
    main()
  File "deus.py", line 92, in main
    worker.run()
  File "/usr/share/git/deus/tellus.py", line 58, in run
    self.loss_provider,
  File "/usr/share/git/deus/gpdexposure.py", line 146, in update_exposure_transitions_and_losses
    pool.map(updater.update_df, splitted_exposure),
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
Exception: ('There is no data for the schema mapping for the source taxonomy CR-LWAL-DNO-H1-3', 'occurred at index 0')

    at org.n52.gfz.riesgos.stderrhandler.PythonTracebackStderrHandler.handleStderr(PythonTracebackStderrHandler.java:57)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService$InnerRunContext.handleStderr(BaseGfzRiesgosService.java:741)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService$InnerRunContext.runExecutableInContext(BaseGfzRiesgosService.java:613)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService$InnerRunContext.runExecutable(BaseGfzRiesgosService.java:540)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService$InnerRunContext.run(BaseGfzRiesgosService.java:438)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService$InnerRunContext.access$100(BaseGfzRiesgosService.java:405)
    at org.n52.gfz.riesgos.algorithm.BaseGfzRiesgosService.run(BaseGfzRiesgosService.java:310)
    at org.n52.wps.server.request.ExecuteRequestV100.call(ExecuteRequestV100.java:678)
    at org.n52.wps.server.request.ExecuteRequestV100.call(ExecuteRequestV100.java:97)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)</ows:ExceptionText></ows:Exception></ows:ExceptionReport></wps:ProcessFailed></wps:Status></wps:ExecuteResponse>
    at WpsClient.parseResponseForErrors (C:\\Users\\lang_m13\\Desktop\\code\\js\\ukis_projects\\dlr-riesgos-frontend\\middleware\\build\\wps\\lib\\wpsclient.js:232:19)
    at Object.next (C:\\Users\\lang_m13\\Desktop\\code\\js\\ukis_projects\\dlr-riesgos-frontend\\middleware\\build\\wps\\lib\\wpsclient.js:228:166)
    at C:\\Users\\lang_m13\\Desktop\\code\\js\\ukis_projects\\dlr-riesgos-frontend\\middleware\
ode_modules\\rxjs\\dist\\cjs\\internal\\operators\    ap.js:20:81
    at OperatorSubscriber._this._next (C:\\Users\\lang_m13\\Desktop\\code\\js\\ukis_projects\\dlr-riesgos-frontend\\middleware\
ode_modules\\rxjs\\dist\\cjs\\internal\\operators\\OperatorSubscriber.js:33:21)
    at OperatorSubscriber.Subscriber.next (C:\\Users\\lang_m13\\Desktop\\code\\js\\ukis_projects\\dlr-riesgos-frontend\\middleware\
ode_modules\\rxjs\\dist\\cjs\\internal\\Subscriber.js:51:18)
    at OperatorSubscriber.Subscriber._next (C:\\Users\\lang_m13\\Desktop\\code\\js\\ukis_projects\\dlr-riesgos-frontend\\middleware\
ode_modules\\rxjs\\dist\\cjs\\internal\\Subscriber.js:80:26)
    at OperatorSubscriber.Subscriber.next (C:\\Users\\lang_m13\\Desktop\\code\\js\\ukis_projects\\dlr-riesgos-frontend\\middleware\
ode_modules\\rxjs\\dist\\cjs\\internal\\Subscriber.js:51:18)
    at C:\\Users\\lang_m13\\Desktop\\code\\js\\ukis_projects\\dlr-riesgos-frontend\\middleware\
ode_modules\\rxjs\\dist\\cjs\\internal\\observable\\innerFrom.js:120:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by nbrinckm** [comment]
Stupid question: Which chile exposure model was used? (For the sara downscaled exposure model will not work. If the others don't work we have to check that together with Camilo.)

**Comment by MichaelLangbein** [comment]
> Stupid question: Which chile exposure model was used? (For the sara downscaled exposure model will not work. If the others don't work we have to check that together with Camilo.)

Eyyy, Nils!
This used the model 'ValpCVTBayesian'. It should be the one behind that link https://rz-vm140.gfz-potsdam.de:8443/wps/RetrieveResultServlet?id=235c0415-fc21-4d25-bcad-eee2f0968eb1merged_output.1a540c29-6d30-48a6-9a93-e0c5959ae7ad , i.e. the one with building-classes like those: "CR-LWAL-DNO-H1-3", "CR-LWAL-DNO-H4-7", "CR-LWAL-DNO-H4-7", "CR-LWAL-DNO-H4-7"

**Comment by nbrinckm** [comment]
Ok, I asked Camilo about the schema mapping.
As far as I understand we really need to support this building class.

It is also part of the "main" building classes that Camilo & Max defined to use for valparaiso: https://link.springer.com/article/10.1007/s10518-021-01312-9/tables/1

And(!) we alreay have the files for the damage state mapping (but not for the taxonomy mapping).

**Comment by nbrinckm** [comment]
I also added now a full test to map the data to medina - so once https://git.gfz-potsdam.de/id2/riesgos/deus/-/merge_requests/12 passes the tests, we can be sure that this schema mapping works just fine.

**Comment by MichaelLangbein** [comment]
New data will be provided by Camilo.
