### ISSUE TITLE
Tsnunami Service error

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/dlr-riesgos-frontend#147]
Target:
http://tsunami-wps.awi.de/wps --- get_scenario

Request:
```xml
<wps:Execute xmlns:wps="http://www.opengis.net/wps/1.0.0" service="WPS" version="1.0.0">
    <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">get_scenario</p0:Identifier>
    <wps:DataInputs>
        <wps:Input>
            <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">lon</p0:Identifier>
            <p0:Title xmlns:p0="http://www.opengis.net/ows/1.1">lon</p0:Title>
            <p0:Abstract xmlns:p0="http://www.opengis.net/ows/1.1"></p0:Abstract>
            <wps:Data>
                <wps:LiteralData>-72.3538</wps:LiteralData>
            </wps:Data>
        </wps:Input>
        <wps:Input>
            <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">lat</p0:Identifier>
            <p0:Title xmlns:p0="http://www.opengis.net/ows/1.1">lat</p0:Title>
            <p0:Abstract xmlns:p0="http://www.opengis.net/ows/1.1"></p0:Abstract>
            <wps:Data>
                <wps:LiteralData>-31.9306</wps:LiteralData>
            </wps:Data>
        </wps:Input>
        <wps:Input>
            <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">mag</p0:Identifier>
            <p0:Title xmlns:p0="http://www.opengis.net/ows/1.1">mag</p0:Title>
            <p0:Abstract xmlns:p0="http://www.opengis.net/ows/1.1"></p0:Abstract>
            <wps:Data>
                <wps:LiteralData>8.0</wps:LiteralData>
            </wps:Data>
        </wps:Input>
    </wps:DataInputs>
    <wps:ResponseForm>
        <wps:ResponseDocument storeExecuteResponse="true" status="true">
            <wps:Output mimeType="string" asReference="false">
                <p0:Identifier xmlns:p0="http://www.opengis.net/ows/1.1">epiCenter</p0:Identifier>
            </wps:Output>
        </wps:ResponseDocument>
    </wps:ResponseForm>
</wps:Execute>
```
Error:
```
Request failed with status code 500
```
Stack:
```
Error: Request failed with status code 500
    at createError (C:\Users\lang_m13\Desktop\code\js\ukis_projects\dlr-riesgos-frontend\middleware\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\lang_m13\Desktop\code\js\ukis_projects\dlr-riesgos-frontend\middleware\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\lang_m13\Desktop\code\js\ukis_projects\dlr-riesgos-frontend\middleware\node_modules\axios\lib\adapters\http.js:322:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
Time:
Sun Apr 24 2022 13:29:36 GMT+0200 (Mitteleuropäische Sommerzeit)

**Comment by MichaelLangbein** [comment]
Making that same request directly over postman gives me the error message:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- PyWPS 4.3.dev0 -->
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="1.0.0">
    <ows:Exception exceptionCode="NoApplicableCode" locator="" >
        <ows:ExceptionText>No applicable error code, please check error log.</ows:ExceptionText>
    </ows:Exception>
</ows:ExceptionReport>
```
