### ISSUE TITLE
Ecuador: Sysrel error

### ISSUE THREAD

**Issue by MichaelLangbein** [riesgos/dlr-riesgos-frontend#148]
Target:
https://riesgos.52north.org/javaps/service --- org.n52.gfz.riesgos.algorithm.impl.SystemReliabilityMultiProcess

Request:
```xml
<wps:Execute xmlns:wps="http://www.opengis.net/wps/2.0" service="WPS" version="2.0.0" mode="async" response="document">
    <p0:Identifier xmlns:p0="http://www.opengis.net/ows/2.0">org.n52.gfz.riesgos.algorithm.impl.SystemReliabilityMultiProcess</p0:Identifier>
    <wps:Input id="height">
        <wps:Reference p1:href="https://riesgos.52north.org/geoserver/ows?service=WPS&version=1.0.0&request=GetExecutionResult&executionId=629ee7e8-1249-4e24-9492-b6fb73253a9b&outputId=shakemap.xml&mimetype=application%2Fxml" xmlns:p1="http://www.w3.org/1999/xlink" mimeType="text/xml"/>
    </wps:Input>
    <wps:Input id="velocity">
        <wps:Reference p2:href="https://riesgos.52north.org/geoserver/ows?service=WPS&version=1.0.0&request=GetExecutionResult&executionId=00265b35-cd26-477e-9cc3-600dc221972e&outputId=shakemap.xml&mimetype=application%2Fxml" xmlns:p2="http://www.w3.org/1999/xlink" mimeType="text/xml"/>
    </wps:Input>
    <wps:Input id="country">
        <wps:Data mimeType="text/plain">ecuador</wps:Data>
    </wps:Input>
    <wps:Input id="hazard">
        <wps:Data mimeType="text/plain">lahar</wps:Data>
    </wps:Input>
    <wps:Output id="damage_consumer_areas" transmission="value" mimeType="application/vnd.geo+json"/>
</wps:Execute>
```
Error:
```
From https://riesgos.52north.org/javaps/service:  <?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/2.0 http://schemas.opengis.net/ows/2.0/owsAll.xsd" version="1.1.0">
  <ows:Exception exceptionCode="NoApplicableCode">
    <ows:ExceptionText>An error occured when parsing the request! Message: The reference to entity "version" must end with the ';' delimiter.</ows:ExceptionText>
    <ows:ExceptionText>[EXCEPTION]: 
org.n52.shetland.ogc.ows.exception.NoApplicableCodeException: An error occured when parsing the request! Message: The reference to entity "version" must end with the ';' delimiter.
	at org.n52.iceland.binding.AbstractXmlBinding.getDecoderKey(AbstractXmlBinding.java:144)
	at org.n52.iceland.binding.AbstractXmlBinding.decode(AbstractXmlBinding.java:82)
	at org.n52.iceland.binding.pox.PoxBinding.parseRequest(PoxBinding.java:95)
	at org.n52.iceland.binding.pox.PoxBinding.doPostOperation(PoxBinding.java:83)
	at org.n52.iceland.service.Service.post(Service.java:149)
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:208)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:274)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 365; The reference to entity "version" must end with the ';' delimiter.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.n52.iceland.binding.AbstractXmlBinding.getDecoderKey(AbstractXmlBinding.java:130)
	... 60 more
</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

Stack:
```
Error: From https://riesgos.52north.org/javaps/service:  <?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/2.0 http://schemas.opengis.net/ows/2.0/owsAll.xsd" version="1.1.0">
  <ows:Exception exceptionCode="NoApplicableCode">
    <ows:ExceptionText>An error occured when parsing the request! Message: The reference to entity "version" must end with the ';' delimiter.</ows:ExceptionText>
    <ows:ExceptionText>[EXCEPTION]: 
org.n52.shetland.ogc.ows.exception.NoApplicableCodeException: An error occured when parsing the request! Message: The reference to entity "version" must end with the ';' delimiter.
	at org.n52.iceland.binding.AbstractXmlBinding.getDecoderKey(AbstractXmlBinding.java:144)
	at org.n52.iceland.binding.AbstractXmlBinding.decode(AbstractXmlBinding.java:82)
	at org.n52.iceland.binding.pox.PoxBinding.parseRequest(PoxBinding.java:95)
	at org.n52.iceland.binding.pox.PoxBinding.doPostOperation(PoxBinding.java:83)
	at org.n52.iceland.service.Service.post(Service.java:149)
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:208)
	at com.thetransactioncompany.cors.CORSFilter.doFilter(CORSFilter.java:274)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 365; The reference to entity "version" must end with the ';' delimiter.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.n52.iceland.binding.AbstractXmlBinding.getDecoderKey(AbstractXmlBinding.java:130)
	... 60 more
</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>

    at WpsClient.parseResponseForErrors (C:\Users\lang_m13\Desktop\code\js\ukis_projects\dlr-riesgos-frontend\middleware\build\wps\lib\wpsclient.js:234:19)
    at Object.next (C:\Users\lang_m13\Desktop\code\js\ukis_projects\dlr-riesgos-frontend\middleware\build\wps\lib\wpsclient.js:220:176)
    at C:\Users\lang_m13\Desktop\code\js\ukis_projects\dlr-riesgos-frontend\middleware\node_modules\rxjs\dist\cjs\internal\operators\tap.js:20:81
    at OperatorSubscriber._this._next (C:\Users\lang_m13\Desktop\code\js\ukis_projects\dlr-riesgos-frontend\middleware\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:33:21)
    at OperatorSubscriber.Subscriber.next (C:\Users\lang_m13\Desktop\code\js\ukis_projects\dlr-riesgos-frontend\middleware\node_modules\rxjs\dist\cjs\internal\Subscriber.js:51:18)
    at OperatorSubscriber.Subscriber._next (C:\Users\lang_m13\Desktop\code\js\ukis_projects\dlr-riesgos-frontend\middleware\node_modules\rxjs\dist\cjs\internal\Subscriber.js:80:26)
    at OperatorSubscriber.Subscriber.next (C:\Users\lang_m13\Desktop\code\js\ukis_projects\dlr-riesgos-frontend\middleware\node_modules\rxjs\dist\cjs\internal\Subscriber.js:51:18)
    at C:\Users\lang_m13\Desktop\code\js\ukis_projects\dlr-riesgos-frontend\middleware\node_modules\rxjs\dist\cjs\internal\observable\innerFrom.js:120:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
Time:
Sun Apr 24 2022 11:11:06 GMT+0200 (Mitteleuropäische Sommerzeit)

**Comment by MichaelLangbein** [comment]
FWIW: I get different errors when I do and when I don't htmlEncode the URLs in the references:
 - `https://riesgos.52north.org/geoserver/ows?service=WPS&version=1.0.0&request=GetExecutionResult&executionId=629ee7e8-1249-4e24-9492-b6fb73253a9b&outputId=shakemap.xml&mimetype=application%2Fxml`
     - yields `An error occured when parsing the request! Message: The reference to entity "version" must end with the ';' delimiter.`
-  `https://riesgos.52north.org/geoserver/ows?service=WPS&amp;version=1.0.0&amp;request=GetExecutionResult&amp;executionId=629ee7e8-1249-4e24-9492-b6fb73253a9b&amp;outputId=shakemap.xml&amp;mimetype=application%2Fxml`
    - yields `The value 'height' of the parameter 'Input' is invalid: unsupported format`

**Comment by MichaelLangbein** [comment]
Resolved!
Same reason as [chile error](https://github.com/riesgos/dlr-riesgos-frontend/issues/149)
